# ===============
# Settings
# ===============
settings:
  features:
    - position
    - age
    - area
    - sex
    - partner
    - num_child
    - education
    - service_length
    - study_time
    - commute
    - overtime
  categorical_features:
  
  fold_name:  01_kfold
  drop_fname:  
  convert_type: 'raw'
  oof:
    save_oof: True
    concat_oof: False
  std: False
  reduce: False
  metrics: mae

# ===============
# Path
# ===============
path:
  train: ../data/input/train_data.feather
  train_y: ../pickle/salary_raw.pkl
  sample: ../data/input/sample_submission.feather

# ===============
# Model Parameters
# ===============
model_params:
    boosting_type: gbdt
    objective: regression
    metric: l1
    learning_rate: 0.01
    num_leaves: 31
    max_depth: 7
    colsample_bytree: 0.8
    bagging_fraction: 0.8
    bagging_freq: 1
    bagging_seed: 11
    max_bin: 255
    verbose: -1
    nthread: -1
    seed: 2019