# ===============
# Settings
# ===============
settings:
  features:
    - position
    - age
    - area
    - area_count_encoding
    - sex
    - partner
    - num_child
    - num_family
    - education
    - service_length
    - study_time
    - commute
    - overtime
    - position_area
    - age_div_mean_each_position
    - partner_div_mean_each_position
    - num_child_div_mean_each_position
    - education_div_mean_each_position
    - service_length_div_mean_each_position
    - study_time_div_mean_each_position
    - commute_div_mean_each_position
    - overtime_div_mean_each_position
    - age_div_mean_each_area
    - partner_div_mean_each_area
    - num_child_div_mean_each_area
    - education_div_mean_each_area
    - service_length_div_mean_each_area
    - study_time_div_mean_each_area
    - commute_div_mean_each_area
    - overtime_div_mean_each_area
    - age_div_mean_each_sex
    - partner_div_mean_each_sex
    - num_child_div_mean_each_sex
    - education_div_mean_each_sex
    - service_length_div_mean_each_sex
    - study_time_div_mean_each_sex
    - commute_div_mean_each_sex
    - overtime_div_mean_each_sex
    - age_div_mean_each_education
    - partner_div_mean_each_education
    - num_child_div_mean_each_education
    - education_div_mean_each_education
    - service_length_div_mean_each_education
    - study_time_div_mean_each_education
    - commute_div_mean_each_education
    - overtime_div_mean_each_education
    - position_target_encoding_folds3
    - area_target_encoding_folds3
    - sex_target_encoding_folds3
    - education_target_encoding_folds3
    - position_education_target_encoding_folds3
  categorical_features:
  
  fold_name:  03_stkfold
  drop_fname:  
  convert_type: raw
  oof:
    save: True
    add: 
  std: False
  reduce: False
  metrics: mae

# ===============
# Path
# ===============
path:
  train: ../data/input/train_data.feather
  train_y: ../pickle/salary_raw.pkl
  sample: ../data/input/sample_submission.feather

# ===============
# Model Parameters
# ===============
model_params:
    boosting_type: gbdt
    objective: regression
    metric: l1
    learning_rate: 0.01
    num_leaves: 31
    max_depth: 7
    colsample_bytree: 0.8
    bagging_fraction: 0.8
    bagging_freq: 1
    bagging_seed: 11
    max_bin: 255
    verbose: -1
    nthread: -1
    seed: 2019